[package]
name = "baa"
version = "0.2.0"
edition = "2021"
authors = ["Kevin Laeufer <laeufer@berkeley.edu>"]
description = "BitVector and Array Arithmetic"
repository = "https://github.com/ekiwi/baa"
license = "BSD-3-Clause"
include = ["Cargo.toml", "LICENSE", "src/", "Readme.md"]
keywords = ["bitvector", "array", "arithmetic"]
readme = "Readme.md"

[dependencies]
smallvec = "1.13.2"
thiserror = "1.0.60"

[dev-dependencies]
proptest = "1.4.0"
